kind: Deployment
apiVersion: apps/v1
metadata:
  name: alertmanager-trigger-k8s-cronjob
  namespace: demo
  labels:
    app: alertmanager-trigger-k8s-cronjob
spec:
  replicas: 2
  selector:
    matchLabels:
      app: alertmanager-trigger-k8s-cronjob
  template:
    metadata:
      labels:
        app: alertmanager-trigger-k8s-cronjob
    spec:
      containers:
        - name: alertmanager-trigger-k8s-cronjob
          image: tinhgin/alertmanager-trigger-k8s-cronjob
          ports:
            - name: http
              containerPort: 5000
              protocol: TCP
          resources:
            limits:
              cpu: '100m'
              memory: "128Mi"
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - alertmanager-trigger-k8s-cronjob
              topologyKey: kubernetes.io/hostname
